import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#f5efe6',
  '--slot4-page-text': '#132a2e',
  '--slot4-panel-bg': '#dde8d2',
  '--slot4-surface-bg': '#fffdf7',
  '--slot4-muted-text': '#526862',
  '--slot4-soft-muted-text': '#71867f',
  '--slot4-accent': '#2f8f83',
  '--slot4-accent-fill': '#244c5a',
  '--slot4-accent-soft': '#c8e5db',
  '--slot4-on-accent': '#fffdf7',
  '--slot4-dark-bg': '#132a2e',
  '--slot4-dark-text': '#fffdf7',
  '--slot4-media-bg': '#f2b66d',
  '--slot4-cream': '#f5efe6',
  '--slot4-warm': '#ead8bd',
  '--slot4-lavender': '#c8d9d1',
  '--slot4-gray': '#a9b8ad',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#f5efe6',
  '--editable-page-text': '#132a2e',
  '--editable-container': '1440px',
  '--editable-border': '#a9b8ad',
  '--editable-nav-bg': '#f5efe6',
  '--editable-nav-text': '#132a2e',
  '--editable-nav-active': '#2f8f83',
  '--editable-nav-active-text': '#132a2e',
  '--editable-cta-bg': '#244c5a',
  '--editable-cta-text': '#fffdf7',
  '--editable-search-bg': '#fffdf7',
  '--editable-footer-bg': '#132a2e',
  '--editable-footer-text': '#fffdf7',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/15',
  shadow: 'shadow-none',
  shadowStrong: 'shadow-[0_24px_70px_rgba(19,42,46,0.16)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(19,42,46,0.05),rgba(19,42,46,0.84))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-6 lg:px-8',
    sectionY: 'py-16 sm:py-20 lg:py-24',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[260px] shrink-0 snap-start sm:w-[320px]',
  },
  type: {
    eyebrow: 'text-xs font-medium uppercase tracking-[0.24em] text-[var(--slot4-accent)]',
    heroTitle: 'text-5xl font-normal leading-[1.08] tracking-[-0.02em] sm:text-6xl lg:text-[5.6rem]',
    sectionTitle: 'text-3xl font-normal leading-[1.15] tracking-[-0.02em] sm:text-5xl',
    body: 'text-base leading-[1.5]',
    emphasis: 'font-normal italic',
  },
  surface: {
    card: `rounded-lg border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-3xl border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-lg ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: 'inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-medium text-[var(--slot4-on-accent)] transition duration-300 hover:bg-[var(--slot4-accent)] hover:text-[var(--slot4-page-text)]',
    secondary: 'inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-transparent px-6 py-3 text-sm font-medium text-[var(--slot4-page-text)] transition duration-300 hover:border-[var(--slot4-page-text)]',
    accent: 'inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent)] px-6 py-3 text-sm font-medium text-[var(--slot4-page-text)] transition duration-300 hover:bg-[var(--slot4-page-text)] hover:text-[var(--slot4-on-accent)]',
    ghost: 'inline-flex items-center justify-center gap-2 rounded-none bg-transparent px-0 py-1 text-sm font-medium text-[var(--slot4-page-text)] transition duration-300 hover:text-[var(--slot4-accent)]',
  },
  badge: {
    pill: 'inline-flex items-center gap-2 rounded-full border border-[var(--editable-border)] px-3 py-1 text-xs font-medium text-[var(--slot4-muted-text)]',
    accentPill: 'inline-flex items-center gap-2 rounded-full bg-[var(--slot4-accent-soft)] px-3 py-1 text-xs font-medium text-[var(--slot4-page-text)]',
  },
  media: {
    frame: `relative overflow-hidden rounded-3xl ${editablePalette.mediaBg}`,
    frameFull: `relative overflow-hidden rounded-lg ${editablePalette.mediaBg}`,
    ratio: 'aspect-[16/10]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-0.5 hover:border-[var(--slot4-page-text)]',
    fade: 'transition duration-300 hover:opacity-75',
    zoom: 'transition duration-700 group-hover:scale-[1.03]',
  },
} as const

export const aiLayoutRules = [
  'Change palette and spacing in editableRootStyle/design-contract first; downstream pages should consume the shared CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so the home experience stays editable in one place.',
  'Use the reference rhythm: fixed-height nav, generous hero, flat cards, pill buttons, and restrained teal accents.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
